# Default values for postgres
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

# This is to override the chart name.
nameOverride: ""
fullnameOverride: ""

# PostgreSQL Configuration
postgres:
  enabled: true

  # PostgreSQL image configuration
  image:
    repository: postgres
    tag: "15.8"
    pullPolicy: IfNotPresent

  # Database configuration
  database:
    name: temporal
    username: temporal
    password: "temporal-dev-password"
    superuser: postgres
    superuserPassword: "postgres-dev-password"

  # Service configuration
  service:
    type: ClusterIP
    port: 5432

  # Storage configuration
  persistence:
    enabled: true
    size: 5Gi
    storageClass: ""
    accessModes:
      - ReadWriteOnce

  # Resources
  resources:
    requests:
      memory: 256Mi
      cpu: 100m
    limits:
      memory: 512Mi
      cpu: 500m

  # Security context
  securityContext:
    enabled: true
    runAsUser: 999
    runAsGroup: 999
    runAsNonRoot: true
    fsGroup: 999

  # Pod security context
  podSecurityContext:
    enabled: true
    runAsUser: 999
    runAsGroup: 999
    runAsNonRoot: true
    fsGroup: 999

  # Environment variables
  env:
    POSTGRES_DB: temporal
    POSTGRES_USER: temporal
    POSTGRES_PASSWORD: temporal-dev-password
    POSTGRES_INITDB_ARGS: "--encoding=UTF-8 --lc-collate=C --lc-ctype=C"

  # Liveness and readiness probes
  livenessProbe:
    enabled: true
    initialDelaySeconds: 30
    periodSeconds: 10
    timeoutSeconds: 5
    failureThreshold: 3
    successThreshold: 1
    exec:
      command:
        - /bin/sh
        - -c
        - exec pg_isready -U "$POSTGRES_USER" -d "$POSTGRES_DB" -h 127.0.0.1 -p 5432

  readinessProbe:
    enabled: true
    initialDelaySeconds: 5
    periodSeconds: 10
    timeoutSeconds: 5
    failureThreshold: 3
    successThreshold: 1
    exec:
      command:
        - /bin/sh
        - -c
        - exec pg_isready -U "$POSTGRES_USER" -d "$POSTGRES_DB" -h 127.0.0.1 -p 5432

# Service Account configuration
serviceAccount:
  # Specifies whether a service account should be created
  create: true
  # Automatically mount a ServiceAccount's API credentials?
  automount: true
  # Annotations to add to the service account
  annotations: {}
  # The name of the service account to use.
  # If not set and create is true, a name is generated using the fullname template
  name: ""

# Node selector
nodeSelector: {}

# Tolerations
tolerations: []

# Affinity
affinity: {}
