{{- if .Values.mongodb.enabled }}
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "mongodb.config.configmap" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "mongodb.labels" . | nindent 4 }}
data:
  mongod.conf: |
{{ .Values.mongodb.configuration | nindent 4 }}
{{- end }}
