{{- if .Values.mongodb.enabled }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "mongodb.secret" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "mongodb.labels" . | nindent 4 }}
type: Opaque
data:
{{- if not .Values.mongodb.auth.existingSecret }}
  mongodb-root-password: {{ include "mongodb.auth.rootPassword" . }}
{{- end }}
{{- end }}
