{{- if .Values.mongodb.enabled }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "mongodb.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "mongodb.labels" . | nindent 4 }}
spec:
  type: {{ .Values.mongodb.service.type }}
  ports:
    - port: {{ .Values.mongodb.service.ports.mongodb }}
      targetPort: mongodb
      protocol: TCP
      name: mongodb
  selector:
    {{- include "mongodb.selectorLabels" . | nindent 4 }}
{{- end }}
