repos:
  # Basic pre-commit hooks
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v6.0.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-added-large-files
      - id: check-merge-conflict
      - id: detect-private-key
      - id: check-merge-conflict
      - id: mixed-line-ending
        args: ["--fix=lf"]

  # Helm chart linting and validation
  - repo: https://github.com/gruntwork-io/pre-commit
    rev: v0.1.30
    hooks:
      - id: helmlint
        args: ["--strict"]
        files: '^helm/.*/Chart\.yaml$'
        exclude: '^helm/.*/templates/.*\.yaml$'
