apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "stackend.fullname" . }}
  labels:
    {{- include "stackend.labels" . | nindent 4 }}
spec:
  {{- if not .Values.autoscaling.enabled }}
  replicas: {{ .Values.replicaCount }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "stackend.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "stackend.selectorLabels" . | nindent 8 }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "stackend.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: http
              containerPort: 8000
              protocol: TCP
            - name: inference
              containerPort: 8888
              protocol: TCP
          {{- if .Values.healthCheck.enabled }}
          livenessProbe:
            httpGet:
              path: /health
              port: http
            initialDelaySeconds: {{ .Values.livenessProbe.initialDelaySeconds }}
            periodSeconds: {{ .Values.livenessProbe.periodSeconds }}
            timeoutSeconds: {{ .Values.livenessProbe.timeoutSeconds }}
            failureThreshold: {{ .Values.livenessProbe.failureThreshold }}
            successThreshold: {{ .Values.livenessProbe.successThreshold }}
          {{- end }}
          {{- if .Values.healthCheck.enabled }}
          readinessProbe:
            httpGet:
              path: /ready
              port: http
            initialDelaySeconds: {{ .Values.readinessProbe.initialDelaySeconds }}
            periodSeconds: {{ .Values.readinessProbe.periodSeconds }}
            timeoutSeconds: {{ .Values.readinessProbe.timeoutSeconds }}
            failureThreshold: {{ .Values.readinessProbe.failureThreshold }}
            successThreshold: {{ .Values.readinessProbe.successThreshold }}
          {{- end }}
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
          env:
            {{- range $key, $value := .Values.env }}
            - name: {{ $key }}
              value: {{ $value | quote }}
            {{- end }}
          volumeMounts:
            - name: llm-config
              mountPath: /app/src/apps/config/llm_config.toml
              subPath: llm_config.toml
            - name: embeddings-config
              mountPath: /app/src/apps/config/embeddings_config.toml
              subPath: embeddings_config.toml
            - name: llm-local-config
              mountPath: /app/src/apps/config/llm_models_by_providers/llm_local_config.toml
              subPath: llm_local_config.toml
            - name: llm-bedrock-config
              mountPath: /app/src/apps/config/llm_models_by_providers/llm_bedrock_config.toml
              subPath: llm_bedrock_config.toml
            - name: llm-azure-config
              mountPath: /app/src/apps/config/llm_models_by_providers/llm_azure_config.toml
              subPath: llm_azure_config.toml
            - name: llm-openai-config
              mountPath: /app/src/apps/config/llm_models_by_providers/llm_openai_config.toml
              subPath: llm_openai_config.toml
      volumes:
        - name: llm-config
          configMap:
            name: {{ include "stackend.fullname" . }}-llm-config
        - name: embeddings-config
          configMap:
            name: {{ include "stackend.fullname" . }}-embeddings-config
        - name: llm-local-config
          configMap:
            name: {{ include "stackend.fullname" . }}-llm-local-config
        - name: llm-bedrock-config
          configMap:
            name: {{ include "stackend.fullname" . }}-llm-bedrock-config
        - name: llm-azure-config
          configMap:
            name: {{ include "stackend.fullname" . }}-llm-azure-config
        - name: llm-openai-config
          configMap:
            name: {{ include "stackend.fullname" . }}-llm-openai-config
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
