stack-repl:
  enabled: true
  image:
    repository: "stackai.azurecr.io/stackai/stack-repl"
    tag: "v1.0.0"
    pullPolicy: IfNotPresent

  # Replica Configuration
  replicaCount: 1

  # Service Configuration
  service:
    type: ClusterIP
    ports:
      http: 8000

  # Resources
  resources:
    requests:
      memory: 256Mi
      cpu: 100m
    limits:
      memory: 512Mi
      cpu: 500m

  # Security Context
  securityContext:
    enabled: true
    runAsUser: 1000
    runAsGroup: 1000
    runAsNonRoot: true

  # Pod Security Context
  podSecurityContext:
    enabled: true
    runAsUser: 1000
    runAsGroup: 1000
    runAsNonRoot: true
    fsGroup: 1000

  # Node Selector
  nodeSelector: {}

  # Tolerations
  tolerations: []

  # Affinity
  affinity: {}

  # Liveness and Readiness Probes
  livenessProbe:
    enabled: false
    httpGet:
      path: /health
      port: http
      scheme: HTTP
    initialDelaySeconds: 30
    periodSeconds: 10
    timeoutSeconds: 5
    failureThreshold: 3
    successThreshold: 1

  readinessProbe:
    enabled: false
    httpGet:
      path: /health
      port: http
      scheme: HTTP
    initialDelaySeconds: 5
    periodSeconds: 5
    timeoutSeconds: 5
    failureThreshold: 3
    successThreshold: 1

# Ingress Configuration
ingress:
  enabled: true
  className: "nginx"
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
    nginx.ingress.kubernetes.io/ssl-redirect: "false"
    cert-manager.io/cluster-issuer: "letsencrypt-prod"
  hosts:
    - host: repl-api.localhost
      paths:
        - path: /
          pathType: Prefix
  tls:
    - secretName: stack-repl-tls
      hosts:
        - repl-api.localhost

# External Secrets Configuration
externalSecrets:
  enabled: false
  # External secret store configuration
  secretStore:
    name: "azure-keyvault-store"
    class: "azure-keyvault"
    # Azure Key Vault configuration
    vaultUrl: "https://your-keyvault.vault.azure.net/"
    tenantId: "your-tenant-id"
    # Service principal for authentication
    servicePrincipal:
      clientId: "your-client-id"
      # Use external secret for client secret
      clientSecretRef:
        name: "azure-keyvault-credentials"
        key: "client-secret"

# Extra objects to be created
extraObjects: []
