stack-repl:
  enabled: true
  image:
    repository: "stackai.azurecr.io/stackai/stackrepl/stack-repl"
    tag: "v1.0.0"
    pullPolicy: IfNotPresent

  # Image pull secrets for private registry
  imagePullSecrets:
    - name: acr-secret

  # Replica Configuration
  replicaCount: 1

  # Service Configuration
  service:
    type: ClusterIP
    ports:
      http: 8000

  # Resources - Increased for macOS local development
  resources:
    requests:
      memory: 1Gi
      cpu: 200m
    limits:
      memory: 2Gi
      cpu: 1000m

  # Security Context
  securityContext:
    enabled: true
    runAsUser: 1000
    runAsGroup: 1000
    runAsNonRoot: true

  # Pod Security Context
  podSecurityContext:
    enabled: true
    runAsUser: 1000
    runAsGroup: 1000
    runAsNonRoot: true
    fsGroup: 1000

  # Node Selector
  nodeSelector: {}

  # Tolerations
  tolerations: []

  # Affinity
  affinity: {}

  # Liveness and Readiness Probes
  livenessProbe:
    enabled: false

  readinessProbe:
    enabled: false

# Ingress Configuration
ingress:
  enabled: true
  className: "nginx"
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
    nginx.ingress.kubernetes.io/ssl-redirect: "false"
    cert-manager.io/cluster-issuer: "letsencrypt-prod"
  hosts:
    - host: repl-api.localhost
      paths:
        - path: /
          pathType: Prefix
  tls:
    - secretName: stack-repl-tls
      hosts:
        - repl-api.localhost

# External Secrets Configuration - DISABLED for development
externalSecrets:
  enabled: false

# Extra objects to be created
extraObjects: []
