stackweb:
  enabled: true
  image:
    repository: "stackai.azurecr.io/stackai/stackweb"
    tag: "v1.0.1"
    pullPolicy: IfNotPresent

  # Image pull secrets for private registry
  imagePullSecrets:
    - name: acr-secret

  # Replica Configuration
  replicaCount: 1

  # Service Configuration
  service:
    type: ClusterIP
    ports:
      http: 3000

  # Resources - Increased for macOS local development
  resources:
    requests:
      memory: 1Gi
      cpu: 200m
    limits:
      memory: 2Gi
      cpu: 1000m

  # Environment Configuration
  env:
    # Next.js Public Variables
    NEXT_PUBLIC_SUPABASE_URL: "http://supabase.localhost"
    NEXT_PUBLIC_URL: "http://stackweb.localhost"
    NEXT_PUBLIC_SITE_URL: "http://stackweb.localhost"
    NEXT_PUBLIC_INDEX_URL: "http://stackend.localhost/"
    NEXT_PUBLIC_CHAT_BACKEND_URL: "http://stackend.localhost/"
    NEXT_PUBLIC_STACKEND_URL: "http://stackend.localhost/"
    NEXT_PUBLIC_STACKEND_INFERENCE_URL: "http://stackend.localhost/"

    # Supabase Keys
    NEXT_PUBLIC_SUPABASE_ANON_KEY: "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZS1kZW1vIiwicm9sZSI6ImFub24iLCJleHAiOjE5ODM4MTI5OTZ9.CRXP1A7WOeoJeXxjNni43kdQwgnWNReilDMblYTn_I0"
    SUPABASE_SERVICE_ROLE_KEY: "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZS1kZW1vIiwicm9sZSI6InNlcnZpY2Vfcm9sZSIsImV4cCI6MTk4MzgxMjk5Nn0.EGIM96RAZx35lJzdJsyH-qQwv8Hdp7fsn3W0YpN81IU"

    # Environment Configuration
    NEXT_PUBLIC_VERCEL_ENV: "production"
    NEXT_PUBLIC_REACT_APP_ENV: "production"
    ON_PREMISE: "true"
    VERCEL_ENV: "production"
    REACT_APP_ENV: "production"

    # Third Party Integrations - Public Keys
    NEXT_PUBLIC_AIRTABLE_CLIENT_ID: "[your-airtable-client-id]"
    NEXT_PUBLIC_AIRTABLE_CODE_VERIFIER: "[your-airtable-code-verifier]"
    NEXT_PUBLIC_CHAMALEON_KEY: "[your-chamaleon-key]"
    NEXT_PUBLIC_DROPBOX_CLIENT_ID: "[your-dropbox-client-id]"
    NEXT_PUBLIC_GOOGLE_CLIENT_ID: "[your-google-client-id]"
    NEXT_PUBLIC_HUBSPOT_CLIENT_ID: "[your-hubspot-client-id]"
    NEXT_PUBLIC_NOTION_CLIENT_ID: "[your-notion-client-id]"
    NEXT_PUBLIC_NOTION_OAUTH_CLIENT_ID: "[your-notion-oauth-client-id]"
    NEXT_PUBLIC_OUTLOOK_CLIENT_ID: "[your-outlook-client-id]"
    NEXT_PUBLIC_POSTHOG_API_KEY: "[your-posthog-api-key]"
    NEXT_PUBLIC_POSTHOG_HOST: "[your-posthog-host]"
    NEXT_PUBLIC_SENTRY_DSN: "[your-sentry-dsn]"
    NEXT_PUBLIC_STRIPE_PUBLISHABLE_KEY: "[your-stripe-publishable-key]"
    NEXT_PUBLIC_TYPEFORM_CLIENT_ID: "[your-typeform-client-id]"
    NEXT_PUBLIC_SHAREPOINT_CLIENT_ID: "[your-sharepoint-client-id]"
    NEXT_PUBLIC_CONFLUENCE_CLIENT_ID: "[your-confluence-client-id]"
    NEXT_PUBLIC_GOOGLE_WORKSPACE_CLIENT_ID: "[your-google-workspace-client-id]"
    NEXT_PUBLIC_STRIPE_CLIENT_ID: "[your-stripe-client-id]"
    NEXT_PUBLIC_ZENDESK_CLIENT_ID: "[your-zendesk-client-id]"
    NEXT_PUBLIC_LEADERBOARD_API_URL: "[your-leaderboard-api-url]"

    # Private Keys
    SHEET_ID: "0"
    RESEND_API_KEY: "[your-resend-api-key]"
    SLACK_CUSTOMER_SUPPORT_WEBHOOK: "[your-slack-customer-support-webhook]"
    SLACK_SELF_HOSTED_WEBHOOK: "[your-slack-self-hosted-webhook]"
    SPREADSHEET_ID: "[your-spreadsheet-id]"
    STRIPE_SECRET_KEY: "[your-stripe-secret-key]"
    STRIPE_WEBHOOK_SECRET: "[your-stripe-webhook-secret]"
    GOOGLE_CLIENT_EMAIL: "mail@example.io"
    GOOGLE_SERVICE_PRIVATE_KEY: "[your-google-service-private-key]"
    FONTAWESOME_PACKAGE_TOKEN: "[your-fontawesome-package-token]"
    TIPTAP_PRO_TOKEN: "[your-tiptap-pro-token]"
    NPM_RC: "[your-npm-rc]"

    # Application settings
    DEBUG: "false"
    ENVIRONMENT: "production"
    LOG_LEVEL: "INFO"
    # Next.js specific settings
    NEXT_TELEMETRY_DISABLED: "1"
    NODE_OPTIONS: "--max-old-space-size=4096"

    # External secrets configuration - DISABLED for development
    secrets:
      useExternalSecrets: false
  # Security Context
  securityContext:
    enabled: true
    runAsUser: 1000
    runAsGroup: 1000
    runAsNonRoot: true
    allowPrivilegeEscalation: false
    capabilities:
      drop:
        - ALL

  # Pod Security Context
  podSecurityContext:
    enabled: true
    runAsGroup: 1000
    runAsNonRoot: false
    fsGroup: 1000
    seccompProfile:
      type: RuntimeDefault

  # Init container to set proper permissions
  initContainers:
    - name: init-permissions
      image: busybox:1.35
      command:
        - sh
        - -c
        - |
          mkdir -p /app/.next /tmp
          chown -R 1000:1000 /app/.next /tmp
          chmod -R 755 /app/.next /tmp
      securityContext:
        runAsUser: 0
        runAsGroup: 0
        allowPrivilegeEscalation: true
      volumeMounts:
        - name: nextjs-cache
          mountPath: /app/.next
        - name: tmp
          mountPath: /tmp

  # Volume mounts for Next.js build cache and temporary files
  volumes:
    - name: nextjs-cache
      emptyDir: {}
    - name: tmp
      emptyDir: {}

  volumeMounts:
    - name: nextjs-cache
      mountPath: /app/.next
    - name: tmp
      mountPath: /tmp

  # Node Selector
  nodeSelector: {}

  # Tolerations
  tolerations: []

  # Affinity
  affinity: {}

  # Liveness and Readiness Probes
  livenessProbe:
    enabled: true
    httpGet:
      path: /
      port: http
      scheme: HTTP
    initialDelaySeconds: 30
    periodSeconds: 10
    timeoutSeconds: 5
    failureThreshold: 3
    successThreshold: 1

  readinessProbe:
    enabled: true
    httpGet:
      path: /
      port: http
      scheme: HTTP
    initialDelaySeconds: 5
    periodSeconds: 5
    timeoutSeconds: 5
    failureThreshold: 3
    successThreshold: 1

# Ingress Configuration
ingress:
  enabled: true
  className: "nginx"
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
    nginx.ingress.kubernetes.io/ssl-redirect: "false"
    cert-manager.io/cluster-issuer: "letsencrypt-prod"
  hosts:
    - host: stackweb.localhost
      paths:
        - path: /
          pathType: Prefix
  tls:
    - secretName: stackweb-tls
      hosts:
        - stackweb.localhost

# External Secrets Configuration - DISABLED for development
externalSecrets:
  enabled: false

# Extra objects to be created
extraObjects: []
