# StackAI Environment ConfigMaps
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: stackend--env
  labels:
    {{- include "stackai-byoc.labels" . | nindent 4 }}
    component: stackend
data:
  # Database Configuration
  DATABASE_URL: "postgresql://postgres:postgres123@{{ include "stackai-byoc.fullname" . }}-supabase-db:5432/postgres"

  # Redis Configuration
  REDIS_URL: "redis://:redis123@{{ include "stackai-byoc.fullname" . }}-redis-master:6379/0"

  # Weaviate Configuration
  WEAVIATE_URL: "http://{{ include "stackai-byoc.fullname" . }}-weaviate:8080"

  # Supabase Configuration
  SUPABASE_URL: "http://{{ include "stackai-byoc.fullname" . }}-supabase-kong:8000"
  SUPABASE_ANON_KEY: "your-anon-key"
  SUPABASE_SERVICE_ROLE_KEY: "your-service-role-key"

  # Application Configuration
  ENVIRONMENT: "production"
  DEBUG: "false"
  LOG_LEVEL: "INFO"

  # API Configuration
  API_HOST: "{{ .Values.stackend.service.host }}"
  API_PORT: "8000"

  # CORS Configuration
  CORS_ORIGINS: "*"

  # Security Configuration
  SECRET_KEY: "your-secret-key"
  JWT_SECRET: "your-jwt-secret"

  # External Services
  OPENAI_API_KEY: "your-openai-key"
  ANTHROPIC_API_KEY: "your-anthropic-key"
  COHERE_API_KEY: "your-cohere-key"

---
apiVersion: v1
kind: ConfigMap
metadata:
  name: stackweb--env
  labels:
    {{- include "stackai-byoc.labels" . | nindent 4 }}
    component: stackweb
data:
  # Next.js Configuration
  NODE_ENV: "production"
  NEXT_PUBLIC_API_URL: "http://{{ include "stackai-byoc.fullname" . }}-stackend:8000"
  NEXT_PUBLIC_WEBSOCKET_URL: "ws://{{ include "stackai-byoc.fullname" . }}-stackend:8000"

  # Supabase Configuration
  NEXT_PUBLIC_SUPABASE_URL: "http://{{ include "stackai-byoc.fullname" . }}-supabase-kong:8000"
  NEXT_PUBLIC_SUPABASE_ANON_KEY: "your-anon-key"

  # Application Configuration
  NEXT_PUBLIC_APP_NAME: "StackAI"
  NEXT_PUBLIC_APP_VERSION: "1.0.0"

  # Feature Flags
  NEXT_PUBLIC_ENABLE_ANALYTICS: "true"
  NEXT_PUBLIC_ENABLE_DEBUG: "false"
