{{- if .Values.externalSecrets.enabled }}
# External Secrets Operator for Azure Key Vault integration
---
apiVersion: external-secrets.io/v1beta1
kind: SecretStore
metadata:
  name: {{ include "stackai-byoc.fullname" . }}-azure-keyvault
  labels:
    {{- include "stackai-byoc.labels" . | nindent 4 }}
spec:
  provider:
    azurekv:
      vaultUrl: {{ .Values.externalSecrets.azureKeyVault.vaultUrl }}
      tenantId: {{ .Values.externalSecrets.azureKeyVault.tenantId }}
      authType: "ClientSecret"
      authSecretRef:
        clientId:
          name: azure-keyvault-secret
          key: client-id
        clientSecret:
          name: azure-keyvault-secret
          key: client-secret

---
apiVersion: v1
kind: Secret
metadata:
  name: azure-keyvault-secret
  labels:
    {{- include "stackai-byoc.labels" . | nindent 4 }}
type: Opaque
data:
  client-id: {{ .Values.externalSecrets.azureKeyVault.clientId | b64enc }}
  client-secret: {{ .Values.externalSecrets.azureKeyVault.clientSecret | b64enc }}

# External Secret for StackAI License
---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: {{ include "stackai-byoc.fullname" . }}-stackend-licence
  labels:
    {{- include "stackai-byoc.labels" . | nindent 4 }}
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: {{ include "stackai-byoc.fullname" . }}-azure-keyvault
    kind: SecretStore
  target:
    name: stackend-licence-secret
    creationPolicy: Owner
  data:
  - secretKey: licence
    remoteRef:
      key: stackai-licence
      property: licence

# External Secret for Database Passwords
---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: {{ include "stackai-byoc.fullname" . }}-database-secrets
  labels:
    {{- include "stackai-byoc.labels" . | nindent 4 }}
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: {{ include "stackai-byoc.fullname" . }}-azure-keyvault
    kind: SecretStore
  target:
    name: supabase-db
    creationPolicy: Owner
  data:
  - secretKey: password
    remoteRef:
      key: database-secrets
      property: postgres-password

# External Secret for API Keys
---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: {{ include "stackai-byoc.fullname" . }}-api-keys
  labels:
    {{- include "stackai-byoc.labels" . | nindent 4 }}
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: {{ include "stackai-byoc.fullname" . }}-azure-keyvault
    kind: SecretStore
  target:
    name: api-keys-secret
    creationPolicy: Owner
  data:
  - secretKey: openai-api-key
    remoteRef:
      key: api-keys
      property: openai-api-key
  - secretKey: anthropic-api-key
    remoteRef:
      key: api-keys
      property: anthropic-api-key
  - secretKey: cohere-api-key
    remoteRef:
      key: api-keys
      property: cohere-api-key
{{- end }}
