{{- if .Values.mongodb.enabled }}
# Custom MongoDB Deployment for ARM64 compatibility
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "stackai-byoc.fullname" . }}-mongodb
  labels:
    {{- include "stackai-byoc.labels" . | nindent 4 }}
    component: mongodb
spec:
  replicas: 1
  selector:
    matchLabels:
      {{- include "stackai-byoc.selectorLabels" . | nindent 6 }}
      component: mongodb
  template:
    metadata:
      labels:
        {{- include "stackai-byoc.selectorLabels" . | nindent 8 }}
        component: mongodb
    spec:
      containers:
        - name: mongodb
          image: "mongo:7.0"
          ports:
            - containerPort: 27017
          env:
            - name: MONGO_INITDB_ROOT_USERNAME
              value: "admin"
            - name: MONGO_INITDB_ROOT_PASSWORD
              value: "mongodb123"
          volumeMounts:
            - name: mongodb-data
              mountPath: /data/db
          resources:
            requests:
              cpu: "100m"
              memory: "256Mi"
            limits:
              cpu: "500m"
              memory: "512Mi"
      volumes:
        - name: mongodb-data
          persistentVolumeClaim:
            claimName: {{ include "stackai-byoc.fullname" . }}-mongodb-pvc

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "stackai-byoc.fullname" . }}-mongodb-pvc
  labels:
    {{- include "stackai-byoc.labels" . | nindent 4 }}
    component: mongodb
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: {{ .Values.global.storageClass }}
  resources:
    requests:
      storage: 5Gi

---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "stackai-byoc.fullname" . }}-mongodb
  labels:
    {{- include "stackai-byoc.labels" . | nindent 4 }}
    component: mongodb
spec:
  type: ClusterIP
  ports:
    - port: 27017
      targetPort: 27017
      protocol: TCP
  selector:
    {{- include "stackai-byoc.selectorLabels" . | nindent 4 }}
    component: mongodb
{{- end }}
