{{- if .Values.configurationSetup.secrets.acrSecret.enabled }}
---
apiVersion: v1
kind: Secret
metadata:
  name: acr-secret
  labels:
    {{- include "stackai-byoc.labels" . | nindent 4 }}
type: kubernetes.io/dockerconfigjson
data:
  .dockerconfigjson: {{ printf "{\"auths\":{\"%s\":{\"username\":\"%s\",\"password\":\"%s\",\"auth\":\"%s\"}}}" .Values.azure.acrName "placeholder" "placeholder" "placeholder" | b64enc }}
{{- end }}

{{- if .Values.configurationSetup.secrets.stackendLicence.enabled }}
---
apiVersion: v1
kind: Secret
metadata:
  name: stackend-licence-secret
  labels:
    {{- include "stackai-byoc.labels" . | nindent 4 }}
type: Opaque
data:
  licence: {{ (index .Values.stackend.secrets 0).data.licence | b64enc }}
{{- end }}

{{- if .Values.supabase.enabled }}
---
apiVersion: v1
kind: Secret
metadata:
  name: supabase-jwt
  labels:
    {{- include "stackai-byoc.labels" . | nindent 4 }}
type: Opaque
data:
  secret: {{ "your-jwt-secret" | b64enc }}

---
apiVersion: v1
kind: Secret
metadata:
  name: supabase-smtp
  labels:
    {{- include "stackai-byoc.labels" . | nindent 4 }}
type: Opaque
data:
  host: {{ "smtp.gmail.com" | b64enc }}
  port: {{ "587" | b64enc }}
  user: {{ "your-email@gmail.com" | b64enc }}
  pass: {{ "your-password" | b64enc }}
  admin_email: {{ "admin@example.com" | b64enc }}
  sender_name: {{ "StackAI" | b64enc }}

---
apiVersion: v1
kind: Secret
metadata:
  name: supabase-dashboard
  labels:
    {{- include "stackai-byoc.labels" . | nindent 4 }}
type: Opaque
data:
  username: {{ "admin" | b64enc }}
  password: {{ "admin123" | b64enc }}

---
apiVersion: v1
kind: Secret
metadata:
  name: supabase-db
  labels:
    {{- include "stackai-byoc.labels" . | nindent 4 }}
type: Opaque
data:
  password: {{ "postgres123" | b64enc }}
{{- end }}
