{{- if .Values.controller.enabled }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "nginx-ingress.controller" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "nginx-ingress.labels" . | nindent 4 }}
  {{- with .Values.controller.service.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  type: {{ .Values.controller.service.type }}
  ports:
    - port: {{ .Values.controller.service.ports.http }}
      targetPort: http
      protocol: TCP
      name: http
    - port: {{ .Values.controller.service.ports.https }}
      targetPort: https
      protocol: TCP
      name: https
  selector:
    {{- include "nginx-ingress.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: controller
{{- end }}
