{{- if .Values.defaultBackend.enabled }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "nginx-ingress.defaultBackend" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "nginx-ingress.labels" . | nindent 4 }}
spec:
  type: ClusterIP
  ports:
    - port: 8080
      targetPort: 80
      protocol: TCP
  selector:
    {{- include "nginx-ingress.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: default-backend
{{- end }}
