{{- if .Values.serviceRouting.enabled }}
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ include "nginx.fullname" . }}-services
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "nginx.labels" . | nindent 4 }}
    app.kubernetes.io/component: service-routing
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
    nginx.ingress.kubernetes.io/ssl-redirect: "false"
    nginx.ingress.kubernetes.io/cors-allow-origin: "*"
    nginx.ingress.kubernetes.io/cors-allow-methods: "GET, POST, PUT, DELETE, OPTIONS"
    nginx.ingress.kubernetes.io/cors-allow-headers: "DNT,User-Agent,X-Requested-With,If-Modified-Since,Cache-Control,Content-Type,Range,Authorization,apikey"
spec:
  ingressClassName: {{ include "nginx.ingressClass" . }}
  rules:
    - host: localhost
      http:
        paths:
          # ArgoCD UI
          - path: /argocd
            pathType: Prefix
            backend:
              service:
                name: argocd-server
                port:
                  number: 80

          # Supabase Services
          - path: /supabase/studio
            pathType: Prefix
            backend:
              service:
                name: supabase-studio
                port:
                  number: 3000
          - path: /supabase/rest
            pathType: Prefix
            backend:
              service:
                name: supabase-kong
                port:
                  number: 8000
          - path: /supabase/auth
            pathType: Prefix
            backend:
              service:
                name: supabase-kong
                port:
                  number: 8000
          - path: /supabase/realtime
            pathType: Prefix
            backend:
              service:
                name: supabase-kong
                port:
                  number: 8000
          - path: /supabase/graphql
            pathType: Prefix
            backend:
              service:
                name: supabase-kong
                port:
                  number: 8000
          - path: /supabase/storage
            pathType: Prefix
            backend:
              service:
                name: supabase-kong
                port:
                  number: 8000
          - path: /supabase/functions
            pathType: Prefix
            backend:
              service:
                name: supabase-kong
                port:
                  number: 8000

          # Temporal Services
          - path: /temporal
            pathType: Prefix
            backend:
              service:
                name: temporal-web
                port:
                  number: 8088

          # Unstructured API
          - path: /unstructured
            pathType: Prefix
            backend:
              service:
                name: unstructured
                port:
                  number: 8000

          # Weaviate
          - path: /weaviate
            pathType: Prefix
            backend:
              service:
                name: weaviate
                port:
                  number: 8080

          # MongoDB (read-only interface if available)
          - path: /mongodb
            pathType: Prefix
            backend:
              service:
                name: mongodb
                port:
                  number: 27017

          # Redis (read-only interface if available)
          - path: /redis
            pathType: Prefix
            backend:
              service:
                name: redis
                port:
                  number: 6379

          # PostgreSQL (read-only interface if available)
          - path: /postgres
            pathType: Prefix
            backend:
              service:
                name: postgres
                port:
                  number: 5432

          # Health check endpoint
          - path: /health
            pathType: Exact
            backend:
              service:
                name: {{ include "nginx.fullname" . }}-default-backend
                port:
                  number: 8080

          # Root redirect to services overview
          - path: /
            pathType: Exact
            backend:
              service:
                name: {{ include "nginx.fullname" . }}-default-backend
                port:
                  number: 8080
{{- end }}
