# StackAI Helm Charts Version Configuration
# This file centralizes version management for all Helm charts

# Chart metadata versions
chartVersion: "1.0.0"
appVersion: "1.0.0"
# Chart versions by category
infrastructure:
  chartVersion: "1.1.2"
  appVersion: "1.1.2"
  components:
    mongodb:
      chartVersion: "1.1.2"
      appVersion: "7.1.2"
    redis:
      chartVersion: "1.1.2"
      appVersion: "7.3.2"
    weaviate:
      chartVersion: "1.1.2"
      appVersion: "1.26.2"
    supabase:
      chartVersion: "1.1.2"
      appVersion: "1.1.2"
    nginx:
      chartVersion: "1.1.2"
      appVersion: "1.10.2"
application:
  chartVersion: "1.1.2"
  appVersion: "1.1.2"
  components:
    stackend:
      chartVersion: "1.1.2"
      appVersion: "1.1.2"
    stackweb:
      chartVersion: "1.1.2"
      appVersion: "1.1.2"
    celery:
      chartVersion: "1.1.2"
      appVersion: "1.1.2"
    repl:
      chartVersion: "1.1.2"
      appVersion: "1.1.2"
# Release information
release:
  name: "stackai-v1.0.1"
  date: "2025-09-22"
  description: "Initial release of StackAI Helm charts with complete infrastructure and application components"
# Version bump strategy
versioning:
  # How to increment versions
  strategy: "semantic"
  # Components that should be updated together
  groups:
    - name: "infrastructure"
      components: ["mongodb", "redis", "weaviate", "supabase", "nginx"]
    - name: "application"
      components: ["stackend", "stackweb", "celery", "repl"]
  # Version bump rules
  rules:
    patch: "Bug fixes, documentation updates"
    minor: "New features, backward compatible changes"
    major: "Breaking changes, incompatible API changes"
