{{- if .Values.stackend.enabled }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "stackai-byoc.fullname" . }}-stackend
  labels:
    {{- include "stackai-byoc.labels" . | nindent 4 }}
    component: stackend
spec:
  replicas: {{ .Values.stackend.replicaCount }}
  selector:
    matchLabels:
      {{- include "stackai-byoc.selectorLabels" . | nindent 6 }}
      component: stackend
  strategy:
      type: Recreate
  template:
    metadata:
      labels:
        {{- include "stackai-byoc.selectorLabels" . | nindent 8 }}
        component: stackend
      annotations:
        checksum/config: {{ include (print $.Template.BasePath "/stackend/configmap.yaml") . | sha256sum }}
    spec:
      {{- with .Values.azure.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.azure.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      containers:
        - name: stackend
          image: "{{ .Values.global.imageRegistry }}/{{ .Values.stackend.image.repository }}:{{ .Values.stackend.image.tag }}"
          imagePullPolicy: {{ .Values.stackend.image.pullPolicy }}
          ports:
            - name: api
              containerPort: {{ .Values.stackend.service.ports.api }}
            - name: debug
              containerPort: {{ .Values.stackend.service.ports.debug }}
          envFrom:
            - configMapRef:
                name: {{ .Values.stackend.env.configMapRef }}
          volumeMounts:
            {{- range .Values.stackend.configMaps }}
            - name: {{ .name }}
              mountPath: /app/src/apps/config/{{ .name | replace "stackend-cm" "" | replace "0" "llm_config.toml" | replace "1" "llm_models_by_providers/llm_local_config.toml" | replace "2" "embeddings_config.toml" }}
              readOnly: true
              subPath: {{ .files | keys | first }}
            {{- end }}
          resources:
            {{- toYaml .Values.stackend.resources | nindent 12 }}
      imagePullSecrets:
        {{- toYaml .Values.global.imagePullSecrets | nindent 8 }}
      restartPolicy: Always
      volumes:
        {{- range .Values.stackend.configMaps }}
        - name: {{ .name }}
          configMap:
            name: {{ .name }}
        {{- end }}
{{- end }}