# StackAI Infrastructure Deployment
# This YAML file deploys all infrastructure components with separate namespaces
# and uses Supabase-style Nginx configuration for local development

---
# MongoDB Namespace
apiVersion: v1
kind: Namespace
metadata:
  name: mongodb
  labels:
    name: mongodb
    app: stackai-infra

---
# Redis Namespace
apiVersion: v1
kind: Namespace
metadata:
  name: redis
  labels:
    name: redis
    app: stackai-infra

---
# Weaviate Namespace
apiVersion: v1
kind: Namespace
metadata:
  name: weaviate
  labels:
    name: weaviate
    app: stackai-infra

---
# Supabase Namespace
apiVersion: v1
kind: Namespace
metadata:
  name: supabase
  labels:
    name: supabase
    app: stackai-infra

---
# Nginx Namespace
apiVersion: v1
kind: Namespace
metadata:
  name: nginx-ingress
  labels:
    name: nginx-ingress
    app: stackai-infra

---
# Nginx Configuration for Supabase-style routing
apiVersion: v1
kind: ConfigMap
metadata:
  name: supabase-nginx-config
  namespace: nginx-ingress
  labels:
    app: supabase-nginx
data:
  nginx.conf: |
    server {
        listen 80;
        server_name localhost;

        # Supabase API routes - proxy to Kong (exactly like your example)
        location /rest/v1/ {
            proxy_pass http://supabase-kong.supabase:8000;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
            proxy_set_header X-Forwarded-Proto $scheme;
        }

        location /graphql/v1/ {
            proxy_pass http://supabase-kong.supabase:8000;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
            proxy_set_header X-Forwarded-Proto $scheme;
        }

        location /auth/v1/ {
            proxy_pass http://supabase-kong.supabase:8000;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
            proxy_set_header X-Forwarded-Proto $scheme;
        }

        location /realtime/v1/ {
            proxy_pass http://supabase-kong.supabase:8000;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
            proxy_set_header X-Forwarded-Proto $scheme;
        }

        location /storage/v1/ {
            proxy_pass http://supabase-kong.supabase:8000;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
            proxy_set_header X-Forwarded-Proto $scheme;
        }

        location /functions/v1/ {
            proxy_pass http://supabase-kong.supabase:8000;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
            proxy_set_header X-Forwarded-Proto $scheme;
        }

        location /analytics/v1/ {
            proxy_pass http://supabase-kong.supabase:8000;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
            proxy_set_header X-Forwarded-Proto $scheme;
        }

        location /sso/ {
            proxy_pass http://supabase-kong.supabase:8000;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
            proxy_set_header X-Forwarded-Proto $scheme;
        }

        # Studio API calls - proxy to Kong for authentication
        location /api/platform/ {
            proxy_pass http://supabase-kong.supabase:8000;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
            proxy_set_header X-Forwarded-Proto $scheme;
        }

        # Studio - direct proxy to studio service
        location /studio/ {
            proxy_pass http://supabase-studio.supabase:3000/;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
            proxy_set_header X-Forwarded-Proto $scheme;
        }

        # Default route - serve a simple status page
        location / {
            return 200 'StackAI Infrastructure is running!\n\nAvailable services:\n- Supabase Studio: /studio/\n- Supabase API: /rest/v1/\n- Auth API: /auth/v1/\n- Realtime: /realtime/v1/\n- Functions: /functions/v1/\n';
            add_header Content-Type text/plain;
        }
    }

---
# Network Policy to allow cross-namespace communication
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: allow-cross-namespace
  namespace: nginx-ingress
spec:
  podSelector: {}
  policyTypes:
    - Ingress
    - Egress
  ingress:
    - from:
        - namespaceSelector: {}
  egress:
    - to:
        - namespaceSelector: {}
