{{- if .Values.meta.enabled -}}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ template "supabase.meta" . }}
  namespace: {{ .Release.Namespace }}
  labels:
{{ include "supabase.labels" . | indent 4 }}
spec:
  ports:
  - name: http
    port: 8080
    targetPort: http
    protocol: TCP
  selector:
{{ include "supabase.selectorLabels" . | indent 4 }}
    app.kubernetes.io/component: meta
{{- end }}
