{{- if .Values.externalSecrets.enabled }}
---
apiVersion: external-secrets.io/v1beta1
kind: SecretStore
metadata:
  name: {{ include "stackend.secretStore" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "stackend.labels" . | nindent 4 }}
spec:
  provider:
    azurekv:
      vaultUrl: {{ .Values.externalSecrets.secretStore.vaultUrl | quote }}
      tenantId: {{ .Values.externalSecrets.secretStore.tenantId | quote }}
      authSecretRef:
        clientId:
          name: {{ .Values.externalSecrets.secretStore.servicePrincipal.clientSecretRef.name }}
          key: {{ .Values.externalSecrets.secretStore.servicePrincipal.clientId | quote }}
        clientSecret:
          name: {{ .Values.externalSecrets.secretStore.servicePrincipal.clientSecretRef.name }}
          key: {{ .Values.externalSecrets.secretStore.servicePrincipal.clientSecretRef.key }}

---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: {{ include "stackend.externalSecret" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "stackend.labels" . | nindent 4 }}
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: {{ include "stackend.secretStore" . }}
    kind: SecretStore
  target:
    name: {{ include "stackend.externalSecret" . }}
    creationPolicy: Owner
  data:
    - secretKey: database-url
      remoteRef:
        key: stackend
        property: database-url
    - secretKey: redis-url
      remoteRef:
        key: stackend
        property: redis-url
    - secretKey: secret-key
      remoteRef:
        key: stackend
        property: secret-key
{{- end }}
