{{- if .Values.stackend.enabled }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "stackend.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "stackend.labels" . | nindent 4 }}
spec:
  type: {{ .Values.stackend.service.type }}
  ports:
    - port: {{ .Values.stackend.service.ports.http }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "stackend.selectorLabels" . | nindent 4 }}
{{- end }}
