{{- if .Values.broker.enabled }}
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "celery.broker" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "celery.labels" . | nindent 4 }}
    app.kubernetes.io/component: broker
spec:
  replicas: {{ .Values.broker.replicaCount }}
  selector:
    matchLabels:
      {{- include "celery.selectorLabels" . | nindent 6 }}
      app.kubernetes.io/component: broker
  template:
    metadata:
      labels:
        {{- include "celery.selectorLabels" . | nindent 8 }}
        app.kubernetes.io/component: broker
    spec:
      {{- with .Values.serviceAccount.create }}
      serviceAccountName: {{ include "celery.serviceAccountName" $ }}
      {{- end }}
      {{- with .Values.broker.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.broker.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.broker.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.broker.securityContext }}
      securityContext:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      containers:
        - name: redis-broker
          image: "{{ .Values.broker.image.repository }}:{{ .Values.broker.image.tag }}"
          imagePullPolicy: {{ .Values.broker.image.pullPolicy }}
          {{- with .Values.broker.podSecurityContext }}
          securityContext:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          ports:
            - name: redis
              containerPort: {{ .Values.broker.service.ports.redis }}
              protocol: TCP
          resources:
            {{- toYaml .Values.broker.resources | nindent 12 }}
{{- end }}
