{{- if .Values.worker.enabled }}
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "celery.worker" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "celery.labels" . | nindent 4 }}
    app.kubernetes.io/component: worker
spec:
  replicas: {{ .Values.worker.replicaCount }}
  selector:
    matchLabels:
      {{- include "celery.selectorLabels" . | nindent 6 }}
      app.kubernetes.io/component: worker
  template:
    metadata:
      labels:
        {{- include "celery.selectorLabels" . | nindent 8 }}
        app.kubernetes.io/component: worker
    spec:
      {{- with .Values.serviceAccount.create }}
      serviceAccountName: {{ include "celery.serviceAccountName" $ }}
      {{- end }}
      {{- with .Values.worker.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.worker.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.worker.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.worker.securityContext }}
      securityContext:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      containers:
        - name: celery-worker
          image: "{{ .Values.worker.image.repository }}:{{ .Values.worker.image.tag }}"
          imagePullPolicy: {{ .Values.worker.image.pullPolicy }}
          {{- with .Values.worker.podSecurityContext }}
          securityContext:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          command:
            - celery
            - -A
            - tasks
            - worker
            - --loglevel=info
          env:
            {{- range $key, $value := .Values.worker.env }}
            {{- if ne $key "secrets" }}
            - name: {{ $key }}
              value: {{ $value | quote }}
            {{- end }}
            {{- end }}
            {{- if .Values.worker.env.secrets.useExternalSecrets }}
            # Environment variables from external secrets
            - name: CELERY_RESULT_BACKEND
              valueFrom:
                secretKeyRef:
                  name: {{ include "celery.externalSecret" . }}
                  key: result-backend
            - name: DATABASE_URL
              valueFrom:
                secretKeyRef:
                  name: {{ include "celery.externalSecret" . }}
                  key: database-url
            {{- end }}
          ports:
            - name: http
              containerPort: {{ .Values.worker.service.ports.http }}
              protocol: TCP
          {{- with .Values.worker.livenessProbe }}
          {{- if .enabled }}
          livenessProbe:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          {{- end }}
          {{- with .Values.worker.readinessProbe }}
          {{- if .enabled }}
          readinessProbe:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          {{- end }}
          resources:
            {{- toYaml .Values.worker.resources | nindent 12 }}
{{- end }}
