apiVersion: v2
name: stackai-stackend
description: Official StackAI Stackend Backend Helm chart.
type: application
version: 1.1.3
appVersion: 1.1.3
icon: https://stackai.com/favicon.ico
keywords:
  - stackai
  - stackend
  - backend
  - api
  - helm
  - chart
  - azure
  - kubernetes
  - aks
  - acr
  - keyvault
home: https://stackai.com
sources:
  - https://github.com/stackai/stackai-helm
maintainers:
  - name: StackAI
    email: support@stackai.com
