{{- if .Values.weaviate.enabled }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "stackai-byoc.fullname" . }}-weaviate
  labels:
    {{- include "stackai-byoc.labels" . | nindent 4 }}
    component: weaviate
spec:
  replicas: 1
  selector:
    matchLabels:
      {{- include "stackai-byoc.selectorLabels" . | nindent 6 }}
      component: weaviate
  template:
    metadata:
      labels:
        {{- include "stackai-byoc.selectorLabels" . | nindent 8 }}
        component: weaviate
    spec:
      containers:
        - name: weaviate
          image: "{{ if .Values.weaviate.image.registry }}{{ .Values.weaviate.image.registry }}/{{ else if .Values.global.imageRegistry }}{{ .Values.global.imageRegistry }}/{{ end }}weaviate/weaviate:{{ .Values.weaviate.image.tag }}"
          ports:
            - name: http
              containerPort: 8080
              protocol: TCP
            - name: grpc
              containerPort: 50051
              protocol: TCP
          env:
            - name: QUERY_DEFAULTS_LIMIT
              value: "100"
            - name: AUTHENTICATION_ANONYMOUS_ACCESS_ENABLED
              value: "true"
            - name: PERSISTENCE_DATA_PATH
              value: "/var/lib/weaviate"
            - name: DEFAULT_VECTORIZER_MODULE
              value: "none"
            - name: CLUSTER_GOSSIP_BIND_PORT
              value: "7100"
            - name: CLUSTER_DATA_BIND_PORT
              value: "7101"
            - name: ENABLE_MODULES
              value: "generative-openai,generative-cohere,generative-palm,generative-anthropic,generative-huggingface,generative-ollama,generative-aws,generative-anyscale,generative-mistral,generative-jina"
          volumeMounts:
            - name: weaviate-data
              mountPath: /var/lib/weaviate
          livenessProbe:
            httpGet:
              path: /v1/.well-known/live
              port: 8080
            initialDelaySeconds: 30
            periodSeconds: 10
          readinessProbe:
            httpGet:
              path: /v1/.well-known/ready
              port: 8080
            initialDelaySeconds: 30
            periodSeconds: 10
          resources:
            {{- toYaml .Values.weaviate.resources | nindent 12 }}
      volumes:
        - name: weaviate-data
          persistentVolumeClaim:
            claimName: {{ include "stackai-byoc.fullname" . }}-weaviate-pvc

{{- end }}
