{{- if .Values.weaviate.enabled }}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "stackai-byoc.fullname" . }}-weaviate-pvc
  labels:
    {{- include "stackai-byoc.labels" . | nindent 4 }}
    component: weaviate
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: {{ .Values.global.storageClass }}
  resources:
    requests:
      storage: {{ .Values.weaviate.persistence.size }}
{{- end }}
