name: Release StackAI Helm Charts

on:
  release:
    types: [published]
  workflow_dispatch:

jobs:
  # Job to validate all infrastructure charts
  validate-infra:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        chart: [mongo, redis, weviate, supabase, nginx]
    steps:
      - name: Checkout
        uses: actions/checkout@v5
        with:
          fetch-depth: 0

      - name: Configure Git
        run: |
          git config user.name "$GITHUB_ACTOR"
          git config user.email "$GITHUB_ACTOR@users.noreply.github.com"

      - name: Set up Helm
        uses: azure/setup-helm@v4
        with:
          version: v3.12.0

      - name: Validate ${{ matrix.chart }} chart
        run: |
          echo "Validating helm/infra/${{ matrix.chart }}"
          helm lint helm/infra/${{ matrix.chart }}
          helm template ${{ matrix.chart }} helm/infra/${{ matrix.chart }}

  # Job to validate all application charts
  validate-app:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        chart: [stackend, stackweb, celery, repl]
    steps:
      - name: Checkout
        uses: actions/checkout@v5
        with:
          fetch-depth: 0

      - name: Configure Git
        run: |
          git config user.name "$GITHUB_ACTOR"
          git config user.email "$GITHUB_ACTOR@users.noreply.github.com"

      - name: Set up Helm
        uses: azure/setup-helm@v4
        with:
          version: v3.12.0

      - name: Validate ${{ matrix.chart }} chart
        run: |
          echo "Validating helm/app/${{ matrix.chart }}"
          helm lint helm/app/${{ matrix.chart }}
          helm template ${{ matrix.chart }} helm/app/${{ matrix.chart }}

  # Job to package charts and update index
  package-and-release:
    needs: [validate-infra, validate-app]
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v5
        with:
          fetch-depth: 0

      - name: Configure Git
        run: |
          git config user.name "$GITHUB_ACTOR"
          git config user.email "$GITHUB_ACTOR@users.noreply.github.com"

      - name: Set up Helm
        uses: azure/setup-helm@v4
        with:
          version: v3.12.0

      - name: Package all charts
        run: |
          echo "Packaging all charts..."
          mkdir -p .cr-release-packages

          # Package infrastructure charts
          for chart in mongo redis weviate supabase nginx; do
            if [ -d "helm/infra/$chart" ]; then
              echo "Packaging helm/infra/$chart"
              helm package helm/infra/$chart --destination .cr-release-packages
            fi
          done

          # Package application charts
          for chart in stackend stackweb celery repl; do
            if [ -d "helm/app/$chart" ]; then
              echo "Packaging helm/app/$chart"
              helm package helm/app/$chart --destination .cr-release-packages
            fi
          done

          echo "Packaging completed"
          ls -la .cr-release-packages/

      - name: Create Helm repository index
        run: |
          echo "Creating Helm repository index..."
          helm repo index .cr-release-packages --url https://stackai.github.io/stackai-helm/

          # Copy index to root
          if [ -f ".cr-release-packages/index.yaml" ]; then
            cp .cr-release-packages/index.yaml index.yaml
            echo "Index file created: index.yaml"
          else
            echo "No index file created"
          fi

      - name: Setup gh-pages branch
        run: |
          # Check if gh-pages branch exists
          if git ls-remote --heads origin gh-pages | grep -q gh-pages; then
            echo "gh-pages branch exists, checking out"
            git checkout gh-pages
            git pull origin gh-pages
          else
            echo "gh-pages branch does not exist, creating it"
            git checkout --orphan gh-pages
            git rm -rf .
          fi

      - name: Commit and push index and packages
        run: |
          git add index.yaml .cr-release-packages/
          git commit -m "chore: update helm repository index and packages" || echo "No changes to commit"
          git push origin gh-pages

      - name: Create release summary
        run: |
          echo "## 🚀 StackAI Helm Charts Release Summary" >> $GITHUB_STEP_SUMMARY
          echo "" >> $GITHUB_STEP_SUMMARY
          echo "### Infrastructure Charts Released:" >> $GITHUB_STEP_SUMMARY
          echo "- mongo" >> $GITHUB_STEP_SUMMARY
          echo "- redis" >> $GITHUB_STEP_SUMMARY
          echo "- weviate" >> $GITHUB_STEP_SUMMARY
          echo "- supabase" >> $GITHUB_STEP_SUMMARY
          echo "- nginx" >> $GITHUB_STEP_SUMMARY
          echo "" >> $GITHUB_STEP_SUMMARY
          echo "### Application Charts Released:" >> $GITHUB_STEP_SUMMARY
          echo "- stackend" >> $GITHUB_STEP_SUMMARY
          echo "- stackweb" >> $GITHUB_STEP_SUMMARY
          echo "- celery" >> $GITHUB_STEP_SUMMARY
          echo "- repl" >> $GITHUB_STEP_SUMMARY
          echo "" >> $GITHUB_STEP_SUMMARY
          echo "### Installation:" >> $GITHUB_STEP_SUMMARY
          echo '```bash' >> $GITHUB_STEP_SUMMARY
          echo 'helm repo add stackai https://stackai.github.io/stackai-helm/' >> $GITHUB_STEP_SUMMARY
          echo 'helm repo update' >> $GITHUB_STEP_SUMMARY
          echo '```' >> $GITHUB_STEP_SUMMARY
