name: Release StackAI Helm Charts

on:
  push:
    branches:
      - main
  workflow_dispatch:
    inputs:
      chart_name:
        description: "Specific chart to release (leave empty for all)"
        required: false
        type: string

jobs:
  # Job to detect which charts have changed
  detect-changes:
    runs-on: ubuntu-latest
    outputs:
      charts: ${{ steps.changes.outputs.charts }}
      infra-charts: ${{ steps.changes.outputs.infra-charts }}
      app-charts: ${{ steps.changes.outputs.app-charts }}
    steps:
      - name: Checkout
        uses: actions/checkout@v5
        with:
          fetch-depth: 0

      - name: Detect changed charts
        id: changes
        run: |
          # Get list of changed files
          if [ "${{ github.event_name }}" = "workflow_dispatch" ] && [ -n "${{ github.event.inputs.chart_name }}" ]; then
            # Manual trigger with specific chart
            echo "charts=${{ github.event.inputs.chart_name }}" >> $GITHUB_OUTPUT
            echo "infra-charts=" >> $GITHUB_OUTPUT
            echo "app-charts=" >> $GITHUB_OUTPUT
          else
            # Detect changes in helm directories
            changed_files=$(git diff --name-only HEAD~1 HEAD)
            infra_charts=""
            app_charts=""

            # Check infrastructure charts
            for chart in mongo redis weviate supabase nginx; do
              if echo "$changed_files" | grep -q "helm/infra/$chart/"; then
                infra_charts="$infra_charts $chart"
              fi
            done

            # Check application charts
            for chart in stackend stackweb celery repl; do
              if echo "$changed_files" | grep -q "helm/app/$chart/"; then
                app_charts="$app_charts $chart"
              fi
            done

            # Combine all charts
            all_charts="$infra_charts $app_charts"
            all_charts=$(echo $all_charts | xargs) # trim whitespace

            echo "charts=$all_charts" >> $GITHUB_OUTPUT
            echo "infra-charts=$infra_charts" >> $GITHUB_OUTPUT
            echo "app-charts=$app_charts" >> $GITHUB_OUTPUT
          fi

  # Job to validate infrastructure charts
  validate-infra:
    needs: detect-changes
    if: needs.detect-changes.outputs.infra-charts != ''
    runs-on: ubuntu-latest
    strategy:
      matrix:
        chart: ${{ fromJson(needs.detect-changes.outputs.infra-charts) }}
    steps:
      - name: Checkout
        uses: actions/checkout@v5
        with:
          fetch-depth: 0

      - name: Configure Git
        run: |
          git config user.name "$GITHUB_ACTOR"
          git config user.email "$GITHUB_ACTOR@users.noreply.github.com"

      - name: Set up Helm
        uses: azure/setup-helm@v4
        with:
          version: v3.12.0

      - name: Validate ${{ matrix.chart }} chart
        run: |
          echo "Validating helm/infra/${{ matrix.chart }}"
          helm lint helm/infra/${{ matrix.chart }}
          helm template ${{ matrix.chart }} helm/infra/${{ matrix.chart }}

  # Job to validate application charts
  validate-app:
    needs: detect-changes
    if: needs.detect-changes.outputs.app-charts != ''
    runs-on: ubuntu-latest
    strategy:
      matrix:
        chart: ${{ fromJson(needs.detect-changes.outputs.app-charts) }}
    steps:
      - name: Checkout
        uses: actions/checkout@v5
        with:
          fetch-depth: 0

      - name: Configure Git
        run: |
          git config user.name "$GITHUB_ACTOR"
          git config user.email "$GITHUB_ACTOR@users.noreply.github.com"

      - name: Set up Helm
        uses: azure/setup-helm@v4
        with:
          version: v3.12.0

      - name: Validate ${{ matrix.chart }} chart
        run: |
          echo "Validating helm/app/${{ matrix.chart }}"
          helm lint helm/app/${{ matrix.chart }}
          helm template ${{ matrix.chart }} helm/app/${{ matrix.chart }}

  # Job to package charts and update index
  package-and-release:
    needs: [detect-changes, validate-infra, validate-app]
    if: always() && (needs.detect-changes.outputs.infra-charts != '' || needs.detect-changes.outputs.app-charts != '')
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v5
        with:
          fetch-depth: 0

      - name: Configure Git
        run: |
          git config user.name "$GITHUB_ACTOR"
          git config user.email "$GITHUB_ACTOR@users.noreply.github.com"

      - name: Set up Helm
        uses: azure/setup-helm@v4
        with:
          version: v3.12.0

      - name: Package all charts
        run: |
          echo "Packaging all charts..."
          mkdir -p .cr-release-packages

          # Package infrastructure charts
          for chart in mongo redis weviate supabase nginx; do
            if [ -d "helm/infra/$chart" ]; then
              echo "Packaging helm/infra/$chart"
              helm package helm/infra/$chart --destination .cr-release-packages
            fi
          done

          # Package application charts
          for chart in stackend stackweb celery repl; do
            if [ -d "helm/app/$chart" ]; then
              echo "Packaging helm/app/$chart"
              helm package helm/app/$chart --destination .cr-release-packages
            fi
          done

          echo "Packaging completed"
          ls -la .cr-release-packages/

      - name: Create Helm repository index
        run: |
          echo "Creating Helm repository index..."
          helm repo index .cr-release-packages --url https://stackai.github.io/stackai-helm/

          # Copy index to root
          if [ -f ".cr-release-packages/index.yaml" ]; then
            cp .cr-release-packages/index.yaml index.yaml
            echo "Index file created: index.yaml"
          else
            echo "No index file created"
          fi

      - name: Commit and push index
        run: |
          git add index.yaml
          git commit -m "chore: update helm repository index" || echo "No changes to commit"
          git push origin gh-pages

      - name: Create release summary
        run: |
          echo "## 🚀 StackAI Helm Charts Release Summary" >> $GITHUB_STEP_SUMMARY
          echo "" >> $GITHUB_STEP_SUMMARY
          echo "### Infrastructure Charts Released:" >> $GITHUB_STEP_SUMMARY
          echo "${{ needs.detect-changes.outputs.infra-charts }}" >> $GITHUB_STEP_SUMMARY
          echo "" >> $GITHUB_STEP_SUMMARY
          echo "### Application Charts Released:" >> $GITHUB_STEP_SUMMARY
          echo "${{ needs.detect-changes.outputs.app-charts }}" >> $GITHUB_STEP_SUMMARY
          echo "" >> $GITHUB_STEP_SUMMARY
          echo "### Installation:" >> $GITHUB_STEP_SUMMARY
          echo '```bash' >> $GITHUB_STEP_SUMMARY
          echo 'helm repo add stackai https://stackai.github.io/stackai-helm/' >> $GITHUB_STEP_SUMMARY
          echo 'helm repo update' >> $GITHUB_STEP_SUMMARY
          echo '```' >> $GITHUB_STEP_SUMMARY
