name: Test Helm Charts

on:
  pull_request:
    branches:
      - main
      - develop
    paths:
      - "helm/**"
  push:
    branches:
      - main
      - develop
    paths:
      - "helm/**"

jobs:
  test-charts:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v5

      - name: Set up Helm
        uses: azure/setup-helm@v4
        with:
          version: v3.12.0

      - name: Test Infrastructure Charts
        run: |
          echo "🧪 Testing Infrastructure Charts..."

          for chart in helm/infra/*/; do
            chart_name=$(basename "$chart")
            echo "Testing $chart_name..."

            # Lint the chart
            helm lint "$chart"

            # Test template rendering
            helm template "$chart_name" "$chart"

            echo "✅ $chart_name passed"
          done

      - name: Test Application Charts
        run: |
          echo "🧪 Testing Application Charts..."

          for chart in helm/app/*/; do
            chart_name=$(basename "$chart")
            echo "Testing $chart_name..."

            # Lint the chart
            helm lint "$chart"

            # Test template rendering
            helm template "$chart_name" "$chart"

            echo "✅ $chart_name passed"
          done

      - name: Success Summary
        run: |
          echo "🎉 All Helm charts built successfully!"
          echo "✅ Infrastructure charts: mongo, redis, weviate, supabase, nginx"
          echo "✅ Application charts: stackend, stackweb, celery, repl"
